### ISSUE TITLE
Would be cool to have forge info set in deployment manifest

### ISSUE THREAD

**Issue by cwb124** [genesis-community/blacksmith-genesis-kit#10]
Instead of hard coding forge releases into the genesis kit, would be cool to make them parameters which would just require a genesis deploy instead of a whole new genesis kit release.  Would help and expedite testing of forge bugs/features and allow more flexibility.

**Comment by cwb124** [comment]
RTFM

**Comment by jhunt** [comment]
For posterity, there is a `params.releases` setting; it's an array that lets you merge in overrides for things like versions and URLs.
