### ISSUE TITLE
boss delete return !!! API 410 Gone

### ISSUE THREAD

**Issue by xiujiao** [genesis-community/blacksmith-genesis-kit#13]
when delete a empty instance, it returns` !!! API 410 Gone`

**Comment by jhunt** [comment]
Can you try a build off of the `gone410` branch?

**Comment by jhunt** [comment]
That's because this issue belongs in https://github.com/jhunt/boss 😉

**Comment by xiujiao** [comment]
haha, I should have thought of that 

Tested the `gone410` branch, it works! `gone 410` is gone

**Comment by jhunt** [comment]
Sweet.  Will merge + release boss v.next today or tomorrow.

**Comment by jhunt** [comment]
Fixed in https://github.com/jhunt/boss/releases/tag/v0.0.3
