### ISSUE TITLE
Azure and AWS IaaS manifests have incorrect instance names

### ISSUE THREAD

**Issue by krutten** [genesis-community/blacksmith-genesis-kit#19]
The Instance name should be Blacksmith or it will complain about missing vm_type

https://github.com/genesis-community/blacksmith-genesis-kit/blob/master/manifests/iaas/azure.yml#L20
https://github.com/genesis-community/blacksmith-genesis-kit/blob/master/manifests/iaas/aws.yml#L26

**Comment by jhunt** [comment]
Fixed in #20
