### ISSUE TITLE
Blacksmith (Internal) BOSH Director .... being deployed as a 'instance group'

### ISSUE THREAD

**Issue by elric392** [genesis-community/blacksmith-genesis-kit#21]
From the description, I would have thought that this BOSH Director would 'run' on the Blacksmith VM.  Not in a separate 'instance group'.

But ran into the issue below when I tried to deploy the kit.

`Task 147 | 04:05:08 | Preparing deployment: Preparing deployment (00:00:01)
                    L Error: Instance group 'bosh' is missing either 'vm_type' or 'vm_resources' or 'resource_pool' section.`

**Comment by jhunt** [comment]
It should all be on a single instance_group, named `blacksmith`.

Can you provide your Genesis environment file(s)?

**Comment by elric392** [comment]
Found out that the 0.4.0 version of the kit (being the latest), doesn't include the commits that removed the 'bosh' instance group.  Also, it still uses the 1.0.3 version of the blacksmith bosh release.

I got around the problem by 'decompiling' the kit .... and manually making the changes to the blacksmith & bosh YAML files, as well as the change to the aws.yml.

Commits .... 
b2026de 
b6f01c2
a7c2468

**Comment by jhunt** [comment]
Ah, you are not on vSphere.  That bug affects the cloud-y infrastructures only.

We'll get a release cut for 0.4.1 with that fix.

**Comment by elric392** [comment]
Thanks.

**Comment by jhunt** [comment]
@dennisjbell can you take a look at this tomorrow?  Pipelines are green so it should be a matter of release notes and a shipit.

**Comment by jhunt** [comment]
I will get this released today.

**Comment by jhunt** [comment]
@elric392 can you give v0.4.1 (https://github.com/genesis-community/blacksmith-genesis-kit/releases/tag/v0.4.1) a whirl?

**Comment by elric392** [comment]
Tested with a 'upgrade' and 'fresh' install.  No longer seeing the above issue.

Thank you.

**Comment by jhunt** [comment]
Thanks for reporting!
