### ISSUE TITLE
Add service name and description params to plan info.

### ISSUE THREAD

**Issue by cwb124** [genesis-community/blacksmith-genesis-kit#3]
Example:

`redis_plans:
    dedicated-persistent:
      description: my-description
      name: my-redis-plan
      type:    standalone
      vm_type: sm-2c-4g
      network: services
      limit:   10
      persist: true
      disk:    8_192`

**Comment by jhunt** [comment]
This is available and working in ccee15a, which once #2 is complete, I'll get released.

**Comment by jhunt** [comment]
Released in 0.1.4 (https://github.com/genesis-community/blacksmith-genesis-kit/releases/tag/v0.1.4)
