### ISSUE TITLE
More service deletion issues

### ISSUE THREAD

**Issue by cwb124** [genesis-community/blacksmith-genesis-kit#9]
Deleting service instances seems problematic.  The VM in the blacksmith broker is not being deleted resulting in quota not being given back.  We have smoke tests that check service creation (and resulting deletion) and this is killing our OSCF environments by eating up quota and leaving orphaned VMs.

**Comment by jhunt** [comment]
Is this still an issue as of 0.3.1?

**Comment by cwb124** [comment]
I believe it was fixed in 0.3.0 but I am testing 0.3.1 in lower today and then into prod. Will update.

**Comment by cwb124** [comment]
Testing was successful.  The last known remaining issue with Blacksmith is https://github.com/genesis-community/blacksmith-genesis-kit/issues/4
